version: "2"
services:
    rabbitmq:
        image: rabbitmq:3.6.5-management
        hostname: rabbitmq_bus
        ports:
            - "15671:15671"
            - "15672:15672"
        networks:
            - main_network
    mongo:
        image: mongo:3.2        
        hostname: mongo_db
        ports:
            - "27017:27017"
        volumes:
            - mongodata:/data/db
        command: --smallfiles --rest --httpinterface
        networks:
            - main_network
        depends_on:
            - rabbitmq    
    node_ingestion:
        image: robymes/node_ingestion:latest
        ports:
            - "8080:8080"
        networks:
            - main_network
        depends_on:
            - rabbitmq
            - mongo            
    node_processing:
        image: robymes/node_processing:latest
        networks:
            - main_network
        depends_on:
            - rabbitmq
            - mongo   
            - node_ingestion         
volumes:
    mongodata:
networks:
    main_network: