version: "2"
services:
    mongo:
        image: mongo:3.2        
        container_name: mongo_db
        hostname: mongo:db
        ports:
            - "27017:27017"
        volumes:
            - mongodata:/data/db
        command: --smallfiles --rest --httpinterface
        networks:
            - main_network
    rabbitmq:
        image: rabbitmq:3.6.5-management
        container_name: rabbitmq_bus
        hostname: rabbitmq_bus
        ports:
            - "15671:15671"
            - "15672:15672"
        networks:
            - main_network
    node_ingestion:
        image: robymes/node_ingestion
        container_name: node_ingestion
        hostname: node_ingestion
        ports:
            - "8080:8080"
        networks:
            - main_network
volumes:
    mongodata:
networks:
    main_network: