version: "2"
services:
    rabbitmq:
        image: rabbitmq:3.6.5-management
        container_name: rabbitmq_bus
        hostname: rabbitmq_bus
        ports:
            - "15671:15671"
            - "15672:15672"
            - "5672:5672"
        networks:
            - main_network
    mongo:
        image: mongo:3.2        
        container_name: mongo_db
        hostname: mongo_db
        ports:
            - "27017:27017"
        volumes:
            - mongodata:/data/db
        command: --smallfiles --rest --httpinterface
        networks:
            - main_network
        depends_on:
            - rabbitmq    
    node_ingestion:
        image: robymes/node_ingestion:latest
        ports:
            - "8080:8080"
        networks:
            - main_network
        depends_on:
            - rabbitmq
            - mongo            
    node_processing:
        image: robymes/node_processing:latest        
        networks:
            - main_network
        depends_on:
            - rabbitmq
            - mongo   
            - node_ingestion   
    aspnet_web:
        image: robymes/aspnet_web:latest
        ports:
            - "5000:80"
        networks:
            - main_network
        depends_on:
            - rabbitmq
            - mongo
            - node_ingestion
            - node_processing      
volumes:
    mongodata:
networks:
    main_network: